#!/bin/bash

video_exists() {
    local id="$1"
    curl --head --fail "https://i.ytimg.com/vi_webp/$id/sddefault.webp" \
        || curl --head --fail "https://i.ytimg.com/vi/$id/hqdefault.jpg"
}

grep --no-filename -E '^\s*[A-Za-z0-9_-]{11}\s' src/data/channel* \
    | awk '{print $1}' \
    | while read id; do
        >/dev/null 2>&1 video_exists "$id" || echo "$id"
        sleep 0.5
    done
