#!/bin/bash

video_exists() {
    local id="$1"
    curl --head --fail "https://i.ytimg.com/vi_webp/$id/sddefault.webp" \
        || curl --head --fail "https://i.ytimg.com/vi/$id/hqdefault.jpg"
}

outfile=/tmp/dead-videos.txt
>&2 echo "writing output to $outfile"

n=0
grep --no-filename -E '^\s*[A-Za-z0-9_-]{11}\s' src/data/channel* \
    | awk '{print $1}' \
    | while read id; do
        >/dev/null 2>&1 video_exists "$id" || echo "$id" | tee --append "$outfile"
        n=$((n+1))
        sleep 0.5
        if [ $((n%250)) -eq 0 ]; then
            >&2 echo $n videos checked
        fi
    done
